"$schema" = 'https://starship.rs/config-schema.json'

continuation_prompt = '> '

# # 2 line prompt
# format = """
# ╭── \
# $os\
# $username\
# $hostname\
# $directory\
# $git_branch\
# $java$nodejs$php$rust$python\
# $sudo\
# $status\
# \n╰─⮞ \
# $container\
# $jobs\
# $character\
# """

# 1 line prompt
format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$java$nodejs$php$rust$python\
$sudo\
$status\
$container\
$jobs\
$character\
"""

[python]
style = 'green bold'
format = '[(\($virtualenv\) )]($style)'

[username]
style_user = 'green'
show_always = false
format = '[$user]($style)'

[hostname]
style = 'green'
ssh_symbol = '@'
format = '[$ssh_symbol$hostname]($style) '

[os]
disabled = true
format = '[$type](bold 202) '

[character]
success_symbol = "\\$"
error_symbol = "\\$"
vimcmd_symbol = "\\$"

[jobs]
format = '[$symbol$number]($style) '
style = 'bold green'
symbol = '◊'
disabled = false

[directory]
style = 'bold blue'
truncation_symbol = '.../'

[git_branch]
format = '[\[$branch(:$remote_branch)\]]($style) '
style = 'bold red'
