# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind-key X kill-session
set -g base-index 1
set -g renumber-windows on
setw -g mode-keys vi
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"
# set-option -g default-shell /bin/zsh

# colors
set -g default-terminal "xterm-256color"
set -g pane-border-style 'fg=white'
set -g pane-active-border-style 'fg=green'
set -as terminal-features ",*:RGB"